apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yfm2bvztp-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-b94b6a0508.8vm0.p3.openshiftapps.com/rhtap/rhtap-qe:1517c9d9f71cc9b995492aecd6f25349be010afc@sha256:33d6361b7357e404e0e922b5bd91e5df70afecf2407f4176062bb35c79a7d6bc
          name: container-image
